### ISSUE TITLE
dedicated data centre channel

### ISSUE THREAD

**Issue by hussainongithub** [networking-discord/networking-discord.github.io#12]
**Is your feature request related to a problem? Please describe.**

Talks about data center things are in a strange mix of general serviceprovidor theproven and enterprise. perhaps it is better to make a data centre channel as the 2 other main 'types' of networks are there already (SP and Ent). it will complete the trifecta perhaps

**Describe the solution you'd like**
channel named datacentre or datacenter 

**Describe alternatives you've considered**
to perhaps talk about DC in SP section, but SP section talks about large geographical distances , heavy MPLS LDP RSVP BGP talks. not that DC doesn't use BGP or even MPLS , its just in a different context to solve a different problem.  i think russ white said that each type of network is a different solution to a different problem, so lets make a channel for the dc problem :D

**Additional context**

proposed solution in screenshot
![image](https://user-images.githubusercontent.com/40867051/108728610-aa82c700-7521-11eb-9677-8075b2554191.png)

**Comment by 1Ludwig** [comment]
Emoji Thumbs up 👍 = Yay
Emoji Thumbs down 👎 = Nay

**Comment by YungTimAllen** [comment]
Voting provisional 👍 with additional requirement that Cloud and Hyperscale discussion/topics be included in the prospective DC channel

**Comment by jrokeach** [comment]
I'd tend to agree. We originally did not create a datacenter channel simply because the number of users on the server at that time did not warrant it, and we didn't want to have a bunch of channels sitting idle. We figured that DC discussion could fit in the SP or Enterprise channels as best appropriate. Now, that's no longer really the case, and there's a decent amount of DC discussion, so I think the reasonable thing would be to go ahead and add it.
